workflow:
  auto_cancel:
    on_new_commit: interruptible

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_BUILDKIT: "1"

  GO_VERSION: "1.25.6"
  GOLANGCI_LINT_VERSION: "v1.64.8"

  BACKEND_IMAGE: "${IMAGE_REGISTRY}/backend"
  TRANSCODER_IMAGE: "${IMAGE_REGISTRY}/transcoder"

  TRIVY_VERSION: "0.48.0"

  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

  ARGOCD_SERVER: "argocd.example.com"
  ARGOCD_VERSION: "2.9.3"

  GITOPS_REPO: "git@gitlab.com:subrotokumar/playstack.git"
  GITOPS_BRANCH: "main"

stages:
  - check
  - quality
  - build
  - container-scan
  - update-manifests
  - sync

include:
  - local: ci/templates.yml
  - local: ci/lint.yml
  - local: ci/test.yml
  - local: ci/quality.yml
  - local: ci/build.yml
  - local: ci/container-scan.yml
  - local: ci/update-manifests.yml
  - local: ci/sync.yml