workflow:
  auto_cancel:
    on_new_commit: interruptible

variables:
  ## CI Veriables
  # IMAGE_REGISTRY: "$IMAGE_REGISTRY"
  # GITOPS_REPO: "$GITOPS_REPO"
  # GITOPS_BRANCH: "$GITOPS_BRANCH"
  # GITLAB_OIDC_TOKEN: "$GITLAB_OIDC_TOKEN"
  # GITLAB_USER_NAME: "$GITLAB_USER_NAME"
  # GITLAB_USER_EMAIL: "$GITLAB_USER_EMAIL"
  # GITOPS_ACCESS_TOKEN: "$GITOPS_ACCESS_TOKEN"
  # AWS_ROLE_ARN: "$AWS_ROLE_ARN"
  # AWS_DEFAULT_REGION: "$AWS_DEFAULT_REGION"
  # SONAR_TOKEN: "$SONAR_TOKEN"

  # Tools Versions
  GO_VERSION: "1.25.6"
  GOLANGCI_LINT_VERSION: "v1.64.8"
  TRIVY_VERSION: "0.48.0"
  
  # Config Settings
  CI_DEBUG_TRACE: "false"
  
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_BUILDKIT: "1"

  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

  # Local Variables
  BACKEND_IMAGE: "${IMAGE_REGISTRY}/backend"
  TRANSCODER_IMAGE: "${IMAGE_REGISTRY}/transcoder"


stages:
  # - check
  # - quality
  - build
  - container-scan
  - update-manifests-dev
  - update-manifests-stage
  - update-manifests-prod

include:
  - local: ci/templates.yml
  # - local: ci/lint.yml
  # - local: ci/test.yml
  # - local: ci/quality.yml
  - local: ci/build.yml
  - local: ci/container-scan.yml
  - local: ci/update-manifests.yml