// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type VideoStatus string

const (
	VideoStatusPREUPLOAD  VideoStatus = "PREUPLOAD"
	VideoStatusUPLOADED   VideoStatus = "UPLOADED"
	VideoStatusPROCESSING VideoStatus = "PROCESSING"
	VideoStatusFAILED     VideoStatus = "FAILED"
	VideoStatusREADY      VideoStatus = "READY"
	VideoStatusPRIVATE    VideoStatus = "PRIVATE"
	VideoStatusPUBLIC     VideoStatus = "PUBLIC"
)

func (e *VideoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VideoStatus(s)
	case string:
		*e = VideoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VideoStatus: %T", src)
	}
	return nil
}

type NullVideoStatus struct {
	VideoStatus VideoStatus `json:"video_status"`
	Valid       bool        `json:"valid"` // Valid is true if VideoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVideoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VideoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VideoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVideoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VideoStatus), nil
}

type Manifest struct {
	ID        uuid.UUID        `json:"id"`
	VideoID   uuid.UUID        `json:"video_id"`
	S3Key     string           `json:"s3_key"`
	Type      string           `json:"type"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type TranscodingJob struct {
	ID           uuid.UUID        `json:"id"`
	VideoID      uuid.UUID        `json:"video_id"`
	Status       interface{}      `json:"status"`
	ErrorMessage pgtype.Text      `json:"error_message"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	Email     string           `json:"email"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Video struct {
	ID          uuid.UUID        `json:"id"`
	UserID      uuid.UUID        `json:"user_id"`
	Title       string           `json:"title"`
	Status      VideoStatus      `json:"status"`
	DurationSec pgtype.Int4      `json:"duration_sec"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type VideoRendition struct {
	ID          uuid.UUID        `json:"id"`
	VideoID     uuid.UUID        `json:"video_id"`
	Resolution  interface{}      `json:"resolution"`
	BitrateKbps int32            `json:"bitrate_kbps"`
	S3Key       string           `json:"s3_key"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
