.build_image:
  extends: .build_ecr_login
  stage: build
  script:
    - |
      export IMAGE_VERSIONED=${TARGET_IMAGE}:${CI_COMMIT_SHORT_SHA}

      docker build \
        --file ${DOCKERFILE} \
        --tag ${IMAGE_VERSIONED} \
        --build-arg VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA} \
        --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
        --build-arg VCS_REF=${CI_COMMIT_SHA} \
        --cache-from ${TARGET_IMAGE}:latest \
        .

      docker push ${IMAGE_VERSIONED}

      if [ -n "$CI_COMMIT_TAG" ]; then
        docker tag ${IMAGE_VERSIONED} ${TARGET_IMAGE}:${CI_COMMIT_TAG}
        docker push ${TARGET_IMAGE}:${CI_COMMIT_TAG}
        docker tag ${IMAGE_VERSIONED} ${TARGET_IMAGE}:latest
        docker push ${TARGET_IMAGE}:latest
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_TAG'


.rules_backend_changes: &backend_changes
  changes:
    - backend/**
    - libs/**

.rules_transcoder_changes: &transcoder_changes
  changes:
    - transcoder/**
    - libs/**

build:backend:
  extends: .build_image
  variables:
    TARGET_IMAGE: ${BACKEND_IMAGE}
    DOCKERFILE: docker/backend.dockerfile
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      <<: *backend_changes
    - if: '$CI_COMMIT_BRANCH == "dev"'
      <<: *backend_changes
    - if: '$CI_COMMIT_TAG'
      <<: *backend_changes


build:transcoder:
  extends: .build_image
  variables:
    TARGET_IMAGE: ${TRANSCODER_IMAGE}
    DOCKERFILE: docker/transcoder.dockerfile
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      <<: *transcoder_changes
    - if: '$CI_COMMIT_BRANCH == "dev"'
      <<: *transcoder_changes
    - if: '$CI_COMMIT_TAG'
      <<: *transcoder_changes