// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Subroto Kumar",
            "url": "http://github.com/subrotokumar/playstack",
            "email": "subrotokumar@outlook.in"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health/liveness": {
            "get": {
                "description": "Indicates whether the application process is alive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "Service is alive",
                        "schema": {
                            "$ref": "#/definitions/server.HealthResponse"
                        }
                    }
                }
            }
        },
        "/health/readiness": {
            "get": {
                "description": "Indicates whether the application is ready to receive traffic",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "Service is ready or not",
                        "schema": {
                            "$ref": "#/definitions/server.HealthResponse"
                        }
                    }
                }
            }
        },
        "/internal/media/videos/{videoId}": {
            "patch": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Updates title, status, or duration of a video",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal"
                ],
                "summary": "Update video metadata (internal)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Video ID",
                        "name": "videoId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Metadata update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.UpdateMetadataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.AssetsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.AssetsResponse"
                        }
                    }
                }
            }
        },
        "/media/videos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns videos with READY status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "List ready videos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.GetVideoResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.GetVideoResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a video record and returns a presigned POST URL for uploading raw media",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Create presigned URL for video upload",
                "parameters": [
                    {
                        "description": "Video asset metadata",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.AssetsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.AssetsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.AssetsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.AssetsResponse"
                        }
                    }
                }
            }
        },
        "/media/videos/{videoId}/thumbnail": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a presigned PUT URL for uploading a video thumbnail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Create presigned URL for thumbnail upload",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Video ID",
                        "name": "videoId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thumbnail metadata",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.ThumbnailAssetsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ThumbnailAssetsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.AssetsResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/server.AssetsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.AssetsResponse"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "description": "Get Profile Detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new user account",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Sign up a new user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    }
                }
            }
        },
        "/profile/sessions": {
            "post": {
                "description": "Authenticate a user and set access/refresh cookies",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    }
                }
            }
        },
        "/profile/tokens": {
            "post": {
                "description": "Refresh access token using refresh token cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Refresh access token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    }
                }
            }
        },
        "/profile/verifications": {
            "post": {
                "description": "Resend confirmation code (OTP) to user's email",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Resend OTP",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    }
                }
            }
        },
        "/profile/verifications/confirm": {
            "post": {
                "description": "Confirm a user's signup using OTP",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Confirm signup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OTP code",
                        "name": "otp",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.AuthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "db.Video": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/pgtype.Timestamp"
                },
                "duration_sec": {
                    "$ref": "#/definitions/pgtype.Int4"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/db.VideoStatus"
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "db.VideoStatus": {
            "type": "string",
            "enum": [
                "PREUPLOAD",
                "UPLOADED",
                "PROCESSING",
                "READY",
                "FAILED"
            ],
            "x-enum-varnames": [
                "VideoStatusPREUPLOAD",
                "VideoStatusUPLOADED",
                "VideoStatusPROCESSING",
                "VideoStatusREADY",
                "VideoStatusFAILED"
            ]
        },
        "pgtype.InfinityModifier": {
            "type": "integer",
            "format": "int32",
            "enum": [
                1,
                0,
                -1
            ],
            "x-enum-varnames": [
                "Infinity",
                "Finite",
                "NegativeInfinity"
            ]
        },
        "pgtype.Int4": {
            "type": "object",
            "properties": {
                "int32": {
                    "type": "integer",
                    "format": "int32"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "pgtype.Timestamp": {
            "type": "object",
            "properties": {
                "infinityModifier": {
                    "$ref": "#/definitions/pgtype.InfinityModifier"
                },
                "time": {
                    "description": "Time zone will be ignored when encoding to PostgreSQL.",
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "server.Asset": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "href": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "original_name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "server.AssetsRequest": {
            "type": "object",
            "required": [
                "content_type",
                "name",
                "size"
            ],
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "server.AssetsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/server.AssetsResponseData"
                },
                "error": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "server.AssetsResponseData": {
            "type": "object",
            "properties": {
                "asset": {
                    "$ref": "#/definitions/server.Asset"
                },
                "form": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "header": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "upload_url": {
                    "type": "string"
                }
            }
        },
        "server.AuthResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/server.Profile"
                },
                "error": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "server.DatabaseHealthStatus": {
            "type": "object",
            "properties": {
                "acquired_conns": {
                    "type": "integer"
                },
                "idle_conns": {
                    "type": "integer"
                },
                "max_conns": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/server.Status"
                },
                "total_conns": {
                    "type": "integer"
                }
            }
        },
        "server.GetVideoResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.Video"
                    }
                },
                "error": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "server.HealthResponse": {
            "type": "object",
            "properties": {
                "db": {
                    "$ref": "#/definitions/server.DatabaseHealthStatus"
                },
                "status": {
                    "$ref": "#/definitions/server.Status"
                }
            }
        },
        "server.Profile": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sub": {
                    "type": "string"
                }
            }
        },
        "server.Status": {
            "type": "string",
            "enum": [
                "UP",
                "DOWN"
            ],
            "x-enum-varnames": [
                "StatusUp",
                "StatusDown"
            ]
        },
        "server.ThumbnailAssetsRequest": {
            "type": "object",
            "required": [
                "content_type",
                "name",
                "size"
            ],
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "server.ThumbnailAssetsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/server.ThumbnailAssetsResponseData"
                },
                "error": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "server.ThumbnailAssetsResponseData": {
            "type": "object",
            "properties": {
                "upload_url": {
                    "type": "string"
                }
            }
        },
        "server.UpdateMetadataRequest": {
            "type": "object",
            "properties": {
                "duration_sec": {
                    "type": "integer"
                },
                "status": {
                    "enum": [
                        "PREUPLOAD",
                        "UPLOADED",
                        "PROCESSING",
                        "READY",
                        "FAILED"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/db.VideoStatus"
                        }
                    ]
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Playstack",
	Description:      "API Dccumentation for Glitch Backend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
